version: '3'

services:
  jekyll:
    build:
      context: .
    command: bundle exec jekyll serve --watch --force_polling --incremental --port 8080 --host 0.0.0.0 --livereload --livereload-port 35729
    volumes:
      - .:/srv/jekyll
    ports:
      - '8080:8080'
      - '35729:35729'
    environment:
      RUBYOPT: '-W0'
      JEKYLL_ENV: production

